- README.md
- src/Lint.jl
- src/linttypes.jl
- Added string method for the lint message for printing, it is basically former show method.
- The show method has been shortened.
- Added linetserver, a function accepting a number which creates an asynchronous server that listens for names of files to lint.
Useful mainly because the firing up julia and linter takes about 10 seconds and even compiling from source with `userimg.jl` does not help. (Unsure why as the code for Lint is pure julia...)
First open julia and do:
````{julia}
using Lint
lintserver(2222)
````
Then from bash you can do (for the first time you might have to do that multiple times because the linting functions are being imported and compiled):
````{bash}
(echo "~/Documents/test.jl"; sleep 2) | nc -w 2 localhost 2222
````
One might create DSL for other linting …
> Adding lintserver for files. 

- src/guesstype.jl
When guessing the type of a call to zeros() or ones() without arguments, a BoundsError is raised.
Test case:
julia> using Lint; lintstr("x = zeros()")
> Prevent a BoundsError

- src/Lint.jl
Currently, incomplete expressions are ignored. For instance, a module missing the "end" keyword reports no errors at all.
Examples:
julia> lintstr("module test; if true; end")
julia> lintstr("2 +")
> Added test for incomplete expressions

- src/functions.jl
Fixes
WARNING: deprecated syntax "Dict{Symbol,Set{DataType}} (" at Lint/src/functions.jl:2.
Use "Dict{Symbol,Set{DataType}}(" instead.
> Fix deprecated syntax "Dict{} (" -> "Dict{}("

- src/functions.jl
- test/funcall.jl
``` julia
julia> lintstr("f(; a)")
ERROR: type Symbol has no field args
in lintfunctioncall at /Users/michaelklassen/.julia/v0.4/Lint/src/functions.jl:525
in lintexpr at /Users/michaelklassen/.julia/v0.4/Lint/src/Lint.jl:149
in lintstr at /Users/michaelklassen/.julia/v0.4/Lint/src/Lint.jl:106
in lintstr at /Users/michaelklassen/.julia/v0.4/Lint/src/Lint.jl:79
```
> Fix exception when passing non expr as keyword arg

- src/functions.jl
- src/variables.jl
- test/globals.jl
``` julia
julia> lintstr("global 5")
ERROR: MethodError: `convert` has no method matching convert(::Type{UTF8String}, ::Int64)
This may have arisen from a call to the constructor UTF8String(...),
since type constructors fall back to convert methods.
Closest candidates are:
call{T}(::Type{T}, ::Any)
convert(::Type{UTF8String}, ::UTF8String)
convert(::Type{UTF8String}, ::ASCIIString)
...
in utf8 at unicode/utf8.jl:233
in lintglobal at /Users/michaelklassen/.julia/v0.4/Lint/src/variables.jl:153
in lintexpr at /Users/michaelklassen/.julia/v0.4/Lint/src/Lint.jl:155
in lintstr at /Users/michaelklassen/.julia/v0.4/Lint/src/Lint.jl:106
in lintstr at /Users/michaelklassen/.julia/v0.4/Lint/src/Lint.jl:79
```
> Convert to string before utf8 if not guaranteed to be string or symbol

- src/Lint.jl
- src/linttypes.jl
- test/runtests.jl
- test/server.jl
Change lintserver to accept code to avoid having to use temp files for unsaved changes.
Change protocol to:
- accept a file name, the amount of code in bytes then the actual code.
- reply with the lint messages sending a empty line to indicated no more messages.
> RFC: Improve lintserver

- src/functions.jl
- test/funcall.jl
This kind of declaration of a function with no methods is allowed by Julia:
```julia
function f end
```
There are many legitimate reasons why this would be useful. However, Lint.jl currently crashes when linting this kind of function. From what I can tell, this was handled correctly once upon a time, since there is code to handle it. However, a fix for another bug has made that code useless. This commit restores that code to the right location. It adds no code except for a single regression test.
> Fix linting of generic function without methods

- src/dict.jl
- test/strings.jl
- test/unusedvar.jl
When linting `Dict` constructors, Lint does not lint the keys, or raw pairs. This causes both false positives:
```julia
function a(x)
Dict(x => 1)
end
```
which results in a spurious "INFO   Argument declared but not used: x", and false negatives:
```julia
function a()
Dict("a" + "b" => 1)
end
```
which results in no error despite the string concatenation problem.
This commit fixes both problems and adds regression tests for both cases.
> Fix incomplete Dict linting

- src/curly.jl
- src/functions.jl
- test/curly.jl
This patch addresses several issues with the old curly linting:
* Fixed false positive: `b = :sym; v = Val{b}`
* Fixed false negative (since 0.4): `Set{(Int, Int)}()` no longer works, but no lint error is raised
* Catch problems like `Array{2, Int}()`
* Catch problems like `Array{Int, 2, 2}()`
* Fixed double linting: `Set{a}()` used to give two undeclared variable errors, even though only one should be raised.
The first change is probably the most important. Julia allows any bitstype to be used as a type parameter, as well as symbols, and this change prevents that from throwing lint errors.
> Better curly linting

- src/linttypes.jl
I think it is more usual to override `show` than to override `string`, since there are 119 methods for `show` but only 14 for `string`. Overriding `show` gives `string` for free, so this reduces the amount of code. There should not be any functional change.
I also deleted the `import Base.show` and `import Base.isless` statements because they were not doing anything, since the methods were defined using the fully-qualified names.
Apologies for the many pull requests; I am trying to get `Currencies.jl` to pass with Lint and there are a few more false positives to sort through. This change is not related to the false positives but I think the simplification is nice.
> Define show() instead of string()

- REQUIRE
- src/Lint.jl
- src/controls.jl
- src/dict.jl
- src/functions.jl
- src/knowndeprec.jl
- src/linttypes.jl
- src/macros.jl
- src/modules.jl
- src/pragma.jl
- src/types.jl
- src/variables.jl
- test/DEMOMODULE.jl
- test/array.jl
- test/doc.jl
- test/funcall.jl
- test/misuse.jl
- test/stagedfuncs.jl
- test/strings.jl
This fixes tests and most deprecations on the latest master. Dict comprehension deprecation is not fixed; that might need to wait for Compat support? Or we can replace it with `Dict([...])`.
> Fix bugs with latest master

- REQUIRE
- docs/getting-started.md
- docs/messages.md
- src/Lint.jl
- src/dict.jl
- src/functions.jl
- src/messages.jl
- src/result.jl
- test/basics.jl
- test/dictkey.jl
- test/globals.jl
- test/import.jl
- test/linthelper.jl
- test/lintself.jl
- test/strings.jl
First commit should be relatively uncontroversial. `String` means something different on 0.5, so this error should be turned off.
Second commit removes message I581, which was never correct. `Dict(:a => 1, :b => 2)` is already a `Dict{Symbol, Int}` and adding in the type annotations is not necessary for better performance.
Third commit replaces `returnMsgs` keyword argument with a `LintResult` type that is always returned, but displays well in multi-line. It retains all the `AbstractVector{LintMessage}` functionality by extending it. While I think this is a good idea, it would be good to get other opinions. (This also fixes #136.)
> Miscellaneous cleanup

- src/controls.jl
- src/linttypes.jl
- src/modules.jl
- test/ifstmt.jl
Sometimes package authors put module loads behind `if` statements, because these module loads might only succeed under particular configurations. We should avoid loading modules protected behind `if` statements, even if it means possible false positives on undefined symbols. It is not sufficient to `try`-`catch` the load, because certain modules call native code and can terminate the entire process if we try to load them. An example is `Dtree.jl`.
Min repro of case this fixes:
```julia
Pkg.add("Dtree")
lintstr("if false; using Dtree; end")
``` 
Fix #149.
> Avoid loading modules protected behind `if`

- docs/messages.md
- src/dict.jl
- src/functions.jl
- src/misc.jl
This code was protected by a less than version 0.4 guard, and since Lint doesn't support 0.3 any more, it's no longer useful. Unfortunately, this doesn't seem to have a visible effect on #156 (since it turns out there isn't much dead code).
> Remove dead code (v0.3-only)

- src/Lint.jl
- src/precompile.jl
Helps #156 (I think there's more we can do for that though.)
On my machine, this shaves about 25% off the time for initial `lintstr` compilation.
> Add a precompile hint for `lintstr`

- src/Lint.jl
- src/dynamic.jl
- src/variables.jl
Avoid using dynamic techniques, which are slow and error-prone, unless absolutely necessary. Remove unnecessary global reregistration, as used globals are not declared globals. Remove spurious temporary variables.
My performance benchmarking suggests a 10% improvement in time to lint Lint itself. This is a first step toward #152.
> Simplify `registersymboluse`

- README.md
Julia 0.3 has not been supported by this package for a long time,
and http://pkg.julialang.org/ no longer lists it.
> Remove Julia 0.3 from README.md

- .travis.yml
All this does is stop testing Travis on v0.4. There is no code change for now. Future PRs can now use 0.5 features without worrying about 0.4 compatibility, and I anticipate that some of the outdated 0.4 code will be removed as we go along.
> Drop v0.4 testing in Travis

- REQUIRE
- src/Lint.jl
- src/controls.jl
- src/curly.jl
- src/dynamic.jl
- src/exprutils.jl
- src/functions.jl
- src/guesstype.jl
- src/knownsyms.jl
- src/linttypes.jl
- src/pragma.jl
- src/ref.jl
- src/statictype.jl
- src/types.jl
- src/variables.jl
- test/array.jl
- test/funcall.jl
- test/misuse.jl
- test/server.jl
- test/stagedfuncs.jl
- test/typecheck.jl
The first commit converts DataType to Type everywhere. This should always have been the case, but is especially important in 0.6, as many types like `Array` are now `UnionAll`s instead of `DataType`s.
The second commit rewrites the version constraint code to not call `eval`. Not calling `eval` is a good idea anyway, but is especially important in 0.6 due to the world age restrictions. The calling of new methods created with `eval` is subject to world age restrictions in 0.6, and removing the `eval` addresses that issue.
The third commit changes from `typeof(x) == T` to `isa(x, T)` in many places. 0.6 introduces new `x isa T` syntax which would make sense to use in the future, and this is a first step toward that modernization.
The fourth commit addresses the remaining, miscellaneous …
> Get Lint working on 0.6

- docs/features.md
- src/Lint.jl
- test/server.jl
Thanks for the good work. I wrote [an Atom package linter-julia](https://github.com/TeroFrondelius/linter-julia), which uses the lintserver(). However, node.js client thinks lintserver isn't closing properly and thus stay busy. Eventually the fix could have been just the close(conn), but I wanted to keep a backward compatibility thus making this `readandwritethestream()` function of the old `@async try` internals solved the trick by itself. At least those two tests, which I added now works with julia 0.5.0.
> Fixing src/Lint.jl lintserver conn to close properly and testing it in test/server.jl

- REQUIRE
- docs/messages.md
- src/Lint.jl
- src/dict.jl
- src/exprutils.jl
- src/functions.jl
- src/guesstype.jl
- src/macros.jl
- src/misc.jl
- src/statictype.jl
- src/types.jl
- src/variables.jl
- test/array.jl
- test/bugs.jl
- test/dictkey.jl
- test/doc.jl
- test/funcall.jl
- test/lintself.jl
- test/runtests.jl
- test/server.jl
- test/typecheck.jl
The first commit deletes a lot of code to guess the return types of function calls in cases where inference can handle it.
The second commit replaces `evaltype` and `parsetype` with a single function that is more general and sophisticated than the existing one.
The third commit deletes a large amount of 0.4-specific code that is no longer necessary, and deletes some uses of `eval` where safer, less dynamic infrastructure exists.
The fourth commit fixes bug #167 and also replaces some uses of `typeof(x) == T` with `isa(x, T)`.
The fifth commit includes tests for all the bugs fixed by this PR, except #167 which is tested in test/docs.jl.
The sixth commit improves the detection of when a type is considered mutable, which fixes several old issues; both #56 and #84 are fixed.
The seventh …
> Simplify code thanks to migration from v0.4

- REQUIRE
- docs/features.md
- src/Lint.jl
- test/server.jl
This pull request is ready. 
TODO:
See issue #131 
Maybe it's ok to list the old issue here to get it closed: #70 
@TotalVerb and @davidanthoff your comments / improvement ideas would be appreciated. 
Ps. I still haven't learned the git. Now it shows all the commits also for the previous pull request.
> Json format return message for lintserver()

- REQUIRE
- docs/features.md
- docs/messages.md
- src/Lint.jl
- src/controls.jl
- src/exprutils.jl
- src/guesstype.jl
- src/macros.jl
- src/modules.jl
- src/result.jl
- src/statictype.jl
- src/types.jl
- src/variables.jl
- test/bugs.jl
- test/forloop.jl
- test/lintself.jl
- test/macro.jl
- test/runtests.jl
- test/server.jl
- test/statictype.jl
- test/tuple.jl
- test/type.jl
- test/typecheck.jl
Instead of using `parameters` which doesn't always work, we fall back to inference to determine the nth element type in static type analysis. Depends on several other PRs to be merged first.
Fixes #180 
Fixes #182 
Introduces E539 to fix #180 and W546 to fix #182.
> Fix #180 by enhancing static type analysis

- src/variables.jl
At the moment only unused variables/arguments called " _ " are ignored. It would be nice if prefixing a variable's name with '_' were sufficient. Among other things, it cuts down on the number of warnings while editing unfinished code, because those would be spurious most of the time anyway. (This is the convention used in Haskell's ghc, for example.)
> Ignore unused vars/args that start with an underscore.

- src/Lint.jl
This has been deprecated for about a year now.  The keyword argument has no effect and can be removed now.
I'll merge once CI passes and then tag a release.
> Remove deprecated returnMsgs keyword argument

- src/statictype.jl
- test/bugs.jl
The check wasn't working as expected because
Union{Tuple{A},Tuple{B}} <: Tuple
Note: in principle, I guess, it should still be possible to figure out if a union of tuples types has all the tuples of the same length, this fix doesn't address that, it just fixes the MethodError.
> Don't call isvatuple on unions of tuples (fixes #215).

- src/Lint.jl
- test/server.jl
I had two fields in cross: excerpt <-> description. This need to be released before linter-julia moves to new linter version, which is much nicer than the current one. Anyway there are no rush, but this is more less patch (bug fix).
> convertmsgtojson() standard-linter-v2 message output fix

- src/knowndeprec.jl
This isn't a real issue at all, just a nitpick, but I'm using STDOUT to communicate with a lint process, and printing non-json messages that aren't real lint messages makes the communication a little messier to parse—the output is no longer even valid json.
> Print non-message to STDERR to avoid confusing emacs.

- src/knowndeprec.jl
Lint was being too picky at startup when trying to read deprecated.jl. We'll have to revisit this code later, but for now we should stop throwing an error when we see something we don't understand.
Ref https://github.com/JuliaLang/julia/pull/21428#issuecomment-296412440
I'll backport this to Lint 0.5, as the latest master may be a disruptive change.
> Fix Lint startup error on 0.6

- src/Lint.jl
- src/knowndeprec.jl
- src/statictype.jl
- test/bugs.jl
- test/server.jl
This backports some smaller, independent minor fixes to 0.5. I will tag 0.6 once the n-pass linter is done; having this release is useful in the interim and in case 0.6 breaks some user code, as it's a disruptive change.
> Backports for Lint 0.5.1

- src/knowndeprec.jl
Fix #229.
From what I can tell, source is not available on all installation, so we cannot figure out the deprecation data this way if it's not available.
(This will be backported to 0.5.2 because 0.6 is not ready for tagging yet.)
> Do not initialize deprecation data if impossible

- .travis.yml
Updates Travis to test on 0.6 too.
I think it's time to tag a final release for 0.5 users, and then remove support for 0.5 and focus on the future.
> Test on 0.6 too

- src/knowndeprec.jl
- src/server.jl
- test/strings.jl
Found some `Compat.UTF8String` and `Compat.ASCIIString`, fixed.
> Fix deprecation warnings

- src/Lint.jl
Closes #257.
Function `lintserver` in `server.jl` uses `listen`, which is now in `Sockets` and need to be improted.
> Import `Sockets` to use `listen`.

- src/cli.jl
- src/include.jl
- src/result.jl
- test/undeclare.jl
1) `open(readstring, f)` replaced by `read(f, String)`
2) `Base.println_with_color` replaced by `Base.printstyled`
> fixed julia 1.0 incompatibilities
